spring.datasource.url=jdbc:h2:mem:locadora;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2

app.security.mode=INSECURE
app.security.encryption-key=9f7c3a4d8b1e2f605a9c7d3e1f8b6a4c5e2d9b7a3c1f8e6d

# Para ativar o laboratório vulnerável, substitua por INSECURE
# app.security.mode=INSECURE
